import { Module } from '@/lib/types';

export const modules: Module[] = [
  {
    id: 'ai-foundations',
    number: 1,
    title: 'Computing and AI Foundations',
    description: 'Start your AI journey by understanding what AI is, how it differs from traditional programming, and explore machine learning fundamentals.',
    topics: [
      'why-learn-ai',
      'what-is-ai',
      'ai-around-us',
      'ai-vs-traditional',
      'intro-machine-learning',
      'types-of-ml',
      'supervised-learning',
      'unsupervised-learning',
      'reinforcement-learning-intro',
      'python-for-ai',
    ],
    totalTopics: 10,
  },
  {
    id: 'machine-learning',
    number: 2,
    title: 'Machine Learning',
    description: 'Dive deep into machine learning concepts, from data preparation to building and evaluating your first ML models.',
    topics: [
      'what-is-ml',
      'data-and-features',
      'training-and-testing',
      'classification',
      'regression',
      'model-evaluation',
      'overfitting-underfitting',
      'intro-scikit-learn',
      'building-ml-model',
    ],
    totalTopics: 9,
  },
  {
    id: 'deep-learning',
    number: 3,
    title: 'Deep Learning',
    description: 'Understand neural networks, how they learn, and build your first deep learning models with modern frameworks.',
    topics: [
      'why-neural-networks',
      'artificial-neuron',
      'activation-functions',
      'neural-network-architecture',
      'forward-propagation',
      'loss-function',
      'gradient-descent',
      'intro-tensorflow',
      'intro-pytorch',
      'building-neural-network',
    ],
    totalTopics: 10,
  },
  {
    id: 'reinforcement-learning',
    number: 4,
    title: 'Reinforcement Learning',
    description: 'Learn how agents learn through interaction, rewards, and experience using reinforcement learning techniques.',
    topics: [
      'what-is-rl',
      'rl-agent',
      'rl-environment',
      'state',
      'action',
      'reward',
      'policy',
      'exploration-exploitation',
      'q-learning',
      'q-table',
      'q-value-update',
      'deep-q-networks',
    ],
    totalTopics: 12,
  },
  {
    id: 'quantum-foundations',
    number: 5,
    title: 'Quantum Computing Foundations',
    description: 'Begin your quantum journey by understanding what makes quantum computers different and the fundamental quantum concepts.',
    topics: [
      'why-learn-quantum',
      'history-of-qc',
      'classical-vs-quantum',
      'what-is-qc',
      'quantum-mechanics-basics',
      'classical-bit',
      'qubit',
      'quantum-state',
      'superposition',
      'measurement',
      'probability-amplitude',
      'entanglement',
      'quantum-interference',
      'qc-applications',
      'qc-limitations',
    ],
    totalTopics: 15,
  },
  {
    id: 'quantum-circuits',
    number: 6,
    title: 'Quantum Circuits and Gates',
    description: 'Learn how to build and manipulate quantum circuits using quantum gates and measurements.',
    topics: [
      'quantum-circuit',
      'quantum-register',
      'quantum-gates',
      'pauli-x-gate',
      'pauli-y-gate',
      'pauli-z-gate',
      'hadamard-gate',
      'controlled-gates',
      'cnot-gate',
      'measurement-qc',
      'building-quantum-circuit',
      'quantum-circuit-simulation',
    ],
    totalTopics: 12,
  },
  {
    id: 'quantum-algorithms',
    number: 7,
    title: 'Quantum Algorithms',
    description: 'Explore fundamental quantum algorithms and understand how they provide advantages over classical approaches.',
    topics: [
      'what-is-quantum-algorithm',
      'quantum-parallelism',
      'deutsch-jozsa',
      'grover-search',
      'quantum-fourier-transform',
      'quantum-algorithm-simulation',
    ],
    totalTopics: 6,
  },
  {
    id: 'quantum-ml',
    number: 8,
    title: 'Quantum Machine Learning',
    description: 'Discover how quantum computing and machine learning combine to create powerful hybrid algorithms.',
    topics: [
      'what-is-qml',
      'why-ai-plus-quantum',
      'quantum-data',
      'classical-data-encoding',
      'quantum-feature-maps',
      'quantum-kernels',
      'variational-quantum-circuits',
      'variational-quantum-classifier',
      'quantum-neural-networks',
      'hybrid-models',
    ],
    totalTopics: 10,
  },
  {
    id: 'quantum-enhanced-ai',
    number: 9,
    title: 'Quantum-Enhanced AI',
    description: 'Explore real-world applications, research directions, and future possibilities of AI and quantum computing integration.',
    topics: [
      'ai-benefits-from-qc',
      'quantum-data-processing',
      'quantum-optimization',
      'hybrid-ai-quantum',
      'ai-quantum-workflow',
      'real-world-applications',
      'research-opportunities',
      'student-projects',
    ],
    totalTopics: 8,
  },
];

export function getModuleById(id: string): Module | undefined {
  return modules.find((m) => m.id === id);
}

export function getModuleByNumber(num: number): Module | undefined {
  return modules.find((m) => m.number === num);
}
